### PR TITLE
Make sure we explicitly skip the 2.7.0 release of less

### LINKED ISSUE #237: gulp-less minor dependency on less introduce : Source map bug introduced in less 2.7.0
Hi

I'm stucked with a less bug : 
**_ Error in plugin 'gulp-less'
Message:
    Invalid mapping: {"generated":{"line":190,"column":2},"source":".../bootstrap/less/print.less","original":{"line":1,"column":null},"name":null} in file undefined line no. undefined
Details:
    lineNumber: undefined
    fileName: undefined_**

I think that you should not reference minor version changes in your package.json for less dependency.

If there are some bugs in dependencies like this one https://github.com/less/less.js/issues/2896 we can't use a previous minor version of gulp-less with a previous less minor version.

You should probably release a gulp-less 3.1.x to point to a less ~2.6.x and upgrade minor of gulp-less when a less minor is released.

### PR DESCRIPTION
**Pull request by wolfy1339**
Would fix #237 by **skipping the 2.7.0 release** altogether and allow users that have 2.6.x installed to keep it when they update gulp-less

### CODE REVIEW

**Comment by stevelacy** [comment]
version `2.7.1` fixes the issues

**Comment by wolfy1339** [comment]
I know that

**Comment by wolfy1339** [comment]
Bump, do you want this PR or are you okay with the less version as it is right now?
Should I just bump less to 2.7.1?

**Comment by stevelacy** [comment]
@contra

**Comment by contra** [comment]
LGTM, if 2.7.1 causes issues it should be removed from the acceptable deps list

**Comment by wolfy1339** [comment]
This PR has been reviewed with a LGTM, and is not merged yet. Just a friendly bump to remind you

**Comment by contra** [comment]
@wolfy1339 Didn't get merged because it wasn't really super urgent, anyone doing `npm update` or `npm install` won't get 2.7.0

**Pull request merged**
