### PR TITLE
less.js version bump

### PR DESCRIPTION
**Pull request by stevenvachon**

### CODE REVIEW

**Comment by contra** [comment]
The current version in the package is equivalent to 2.* (that's what the ^ means), so if you run `npm update` it will update to whatever the latest version is. This change won't make the situation any different.

**Comment by stevenvachon** [comment]
I know, but it's good to keep the package up to date, at least for significant versions. 2.6 introduces support for `@custom-media`.

**Comment by contra** [comment]
@stevenvachon I'm saying if you run `npm install gulp-less` it will install 2.*, so in this case it will install 2.6. There is no change needed, 2.6 already gets installed.

**Comment by stevenvachon** [comment]
I know and I have already done this. My update was merely a semantic update because 2.6 is better.

**Comment by stevenvachon** [comment]
It's no big deal if you feel differently -- just explaining my thought.

**Comment by contra** [comment]
Again, this solved 0 problems. When somebody install `gulp-less` they WILL get 2.6 with the current code. This PR does not change the result at all.

**Pull request closed without merging**
