### PR TITLE
update README.md (Minifying CSS gulp plugin is deprecated)

### PR DESCRIPTION
**Pull request by marti1125**
gulp-minify-css is deprecated replace with gulp-cssnano

https://www.npmjs.com/package/gulp-minify-css#deprecation-warning
https://www.npmjs.com/package/gulp-cssnano

### CODE REVIEW

**Comment by contra** [comment]
Thanks! Appreciate it.

**Comment by contra** [comment]
Could you also send a PR to the plugin blacklist so people don't see gulp-minify-css on the search results?

**Comment by marti1125** [comment]
done! https://github.com/gulpjs/plugins/pull/209

**Comment by marti1125** [comment]
@contra How to I can help with gulpjs?

**Pull request merged**
