### PR TITLE
Correct use of promises.

### LINKED ISSUE #118: Less compilation doesn't break on missing variable
Not sure if this issue should be here or in the less repo, but here it is. I recently did a lot of refactoring and after deleting a certain file, the less task would never finish, which would cause more problems in the default task as you can imagine. After going through all the changes, I found that I had deleted a variable that was used in another file. Even though less should have thrown an error about a missing variable, it didn't.

I'm not sure if I've missed something with less 2.0.0 or if this is a bug between one or both repos.

Thanks!

### PR DESCRIPTION
**Pull request by OhJeez**
fixes #118

Pull request is against v2.0.1 since the newest master broke something in include path resolution.

By using done I made sure that the promise chain won't be interrupted and either the error will be passed to `cb` or the process will crash. Which is still better than error vanishing.

### CODE REVIEW

**Comment by contra** [comment]
Oh so render returns a promise all of the sudden? Interesting

**Comment by OhJeez** [comment]
Well, there was a .then(...) in v2.0.1 already, I just moved things a bit and added .done(). As far as I can tell, less (due to less/less.js#2430) threw an error in the onResolve function, which was the last in chain, so that error never was handled.

**Comment by contra** [comment]
Can you rebase so this can merge? You made the changes on old code

**Comment by OhJeez** [comment]
As I said
> Pull request is against v2.0.1 since the newest master broke something in include path resolution.

I.e.
```
Error in plugin 'gulp-less'
Message:
    'font-awesome/less/variables.less' wasn't found. Tried - /home/ch/gpndata/src/perverse/src/Browser/logged_in/style/font-awesome/less/variables.less,font-awesome/less/variables.less in file /home/ch/gpndata/src/perverse/src/Browser/logged_in/style/config.less line no. 1
Details:
    type: File
    filename: /home/ch/gpndata/src/perverse/src/Browser/logged_in/style/config.less
    index: 0
    line: 1
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: ,@import "font-awesome/less/variables";,
    lineNumber: 1
    fileName: /home/ch/gpndata/src/perverse/src/Browser/logged_in/style/config.less
```
First guess would be something with `lodash.defaults` being replaced by `object-assign`.
Anyway, the same fix is at the top of OhJeez/gulp-less#master. I will make another pull request, but please be aware of the error above (which is not detected by unit tests).

**Comment by contra** [comment]
Duplicate of #132

**Pull request closed without merging**
